project:
  name: corda-aws-qs
  regions:
  - ap-southeast-1
  - us-east-1
  - us-west-2
  - eu-central-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-west-2
    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: garry.jackson@r3.com
      KeyPairName: qs-workshop
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "corda-aws-qs/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"

